### ISSUE TITLE
Usage of deprecated Actions version

### ISSUE THREAD

**Issue by radeusgd** [ayltai/setup-graalvm#6]
The `@actions/core` version `1.2.4` uses [deprecated methods to set environment variables](https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/).

As I can see, the dependabot has automatically updated this and the PR has been merged, but since no release was made, it is not picked up automatically on users' CI.

On the 16th of November the old mechanism will be turned off, hence actions using this one as dependency will stop working. Can we ask for an updated release of this action?

**Comment by ayltai** [comment]
Thank you for letting me know about this. A new release with the same v1 tag has been published to replace the old v1 so there is nothing to change on your side.

**Comment by radeusgd** [comment]
Thanks a lot for the quick response.

We re-run our CI just now, but it seems that somehow it still picks up the old version:
![image](https://user-images.githubusercontent.com/1436948/98650185-d3979700-2338-11eb-96db-dfc510634757.png)

I don't know if it may be a caching issue, but since the update was already 2 hours ago, it seems unlikely. Maybe you could try releasing a bumped version too to ensure one can force the new version?

**Comment by radeusgd** [comment]
I investigated this further - updated our CI to pin to the specific commit and the issue still persists.

Relevant part of our config:
```
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
# [...]
      - name: Setup GraalVM Environment
        uses: ayltai/setup-graalvm@03e7b7557
        with:
          graalvm-version: ${{ env.graalVersion }}
          java-version: ${{ env.javaVersion }}
```

The error is exactly the same as above:
```
Run ayltai/setup-graalvm@03e7b7557
Downloading GraalVM from graalvm/graalvm-ce-builds@vm-20.2.0 graalvm-ce-java11-linux-amd64-20.2.0.tar.gz (download)
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/temp_1514993758 -f /home/runner/work/_temp/0c663c3c-5b07-4249-b5d4-d278cccd999e
Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
Error: The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
/opt/hostedtoolcache/GraalVM/java11-linux-amd64-20.2.0/x64/bin/gu install native-image
```

I'm not sure what may be causing that, as the source code only seems to use `actions/core` for this purpose and it was updated. Maybe the artifacts for the release were not re-built? Just guessing though.

**Comment by radeusgd** [comment]
I have looked into the source code in the `dist` directory inside of the source bundle of the latest release.

It seems that the relevant parts from the `actions/core` still use the old source code (there is the `set-env` logic, but no environment files logic).

So my guess is that the action has not been rebuit before publishing and since the `dist` directory is what is relevant for the GitHub Actions runner, while the new release is published, it still runs the old version.

**Comment by ayltai** [comment]
Thanks for getting that deep into the issue. Indeed, that's one of the causes. Another cause was that `node_modules` was not updated.

I believe it is fixed on the current `master` branch and the `v1` tag.

**Comment by radeusgd** [comment]
It seems to have fixed the issue indeed - the warnings do not show up in our workflows anymore.

Thank you very much for resolving this issue so quickly.
